# Use postgres/example user/password credentials
services:

  postgres:
    image: postgres
    restart: always
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    ports:
      - '5432:5432'

  pgadmin4:
      image: elestio/pgadmin:latest
      restart: always
      environment:
        PGADMIN_DEFAULT_EMAIL: mail@mail.com
        PGADMIN_DEFAULT_PASSWORD: admin
        PGADMIN_LISTEN_PORT: 8080
      ports:
      - '8080:8080'
      volumes:
      - ./servers.json:/pgadmin4/servers.json

#run  docker-compose up -d
# docker inspect xxxx ver ip donde corre el contenedor